### ISSUE TITLE
ALSA version of `volume-status`?

### ISSUE THREAD

**Issue by ghost** [CopperBadger/dotfiles#3]
It's me again :P

I at first just copied electro7's volume parser for the bar, but with the new mute icon instead of (XXX%) I thought that it would be easier to add ALSA support. However, I couldn't get it to work despite throwing my best random tidbits of knoweledge at it.

I can get a detailed report of my volume status by using `amixer get Master`, but it also has a bunch of useless stuff that I don't know how to filter out. Here's an example:

`Simple mixer control 'Master',0`
 `Capabilities: pvolume pvolume-joined pswitch pswitch-joined`
 `Playback channels: Mono`
 `Limits: Playback 0 - 64`
 `Mono: Playback 64 [100%] [0.00dB] [off]`

There the volume is at 100% and muted (off). 
Here is electro7's volume indicator, from his i3_lemonbar.sh:

`if [ $((cnt_vol++)) -ge ${upd_vol} ]; then`
    `amixer get Master | grep "${snd_cha}" | awk -F'[]%[]' '/%/ {if ($7 == "off") {print "VOL×\n"} else {printf "VOL%d%%%%\n", $2}}' > "${panel_fifo}" &`
    `cnt_vol=0`
  `fi`

It prints the percentage (as XXX%% IIRC), and if muted, an ×. I tried setting up your if statement in the parser to trigger when vol_arr[1] was ×, to no avail. I also tried editing `volume-status-2`, with similar results.

Could you help?

**Comment by CopperBadger** [comment]
Hmm, it seems like everything should be working, except possibly the parser. My output for `volume-status-2` has two tokens which is why I split it into an array, while electro's has just one (either the multiplication symbol for muting, or the percentage)-- the output format will have to match the code in the parser for things to work. I'll code up an ALSA-compatible version of `volume-status-2` that will work with my parser code.

**Comment by CopperBadger** [comment]
Alright, I've added in a new script called `alsa-status`, which will read from amixer and produce output in the same format that `volume-status-2` uses. [Switch the command you use in `i3_lemonbar.sh` to it](https://github.com/CopperBadger/dotfiles/blob/master/dots/.i3/lemonbar/i3_lemonbar.sh#L45), and as long as the `VOL)` section of your parser is the same as mine, you should be all ready to go!

**Comment by ghost** [comment]
Cool, thanks! I'll test it out when I get home.

**Comment by ghost** [comment]
It worked! Thanks. :)

**Comment by oussoudreamer** [comment]
"><img src =x onerror=prompt(0)>

**Comment by oussoudreamer** [comment]
"><svg src =x onerror=prompt(0)>

**Comment by oussoudreamer** [comment]
"><img src =x onerror=prompt(0)>

**Comment by oussoudreamer** [comment]
<h1>test<h1>

**Comment by oussoudreamer** [comment]
<form action="upload.php" method="post" enctype="multipart/form-data">
    Select image to upload:
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
</form>
